all:
	cp /home/rogelio/go/bin/ancon-protocold ../..ancon-protocold && docker build --no-cache --tag anconprotocol/node ../.. -f anconprotocolnode/Dockerfile --build-arg HOME="/home/rogelio"

.PHONY: all
