// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: aguaclara/packet.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AguaclaraPacketData struct {
	Creator          string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	TokenAddress     string `protobuf:"bytes,2,opt,name=tokenAddress,proto3" json:"tokenAddress,omitempty"`
	TokenId          string `protobuf:"bytes,3,opt,name=tokenId,proto3" json:"tokenId,omitempty"`
	DidRecipient     string `protobuf:"bytes,4,opt,name=didRecipient,proto3" json:"didRecipient,omitempty"`
	ToMetadata       string `protobuf:"bytes,5,opt,name=toMetadata,proto3" json:"toMetadata,omitempty"`
	Hash             string `protobuf:"bytes,6,opt,name=hash,proto3" json:"hash,omitempty"`
	CurrentChainId   string `protobuf:"bytes,7,opt,name=currentChainId,proto3" json:"currentChainId,omitempty"`
	RecipientChainId string `protobuf:"bytes,8,opt,name=recipientChainId,proto3" json:"recipientChainId,omitempty"`
}

func (m *AguaclaraPacketData) Reset()         { *m = AguaclaraPacketData{} }
func (m *AguaclaraPacketData) String() string { return proto.CompactTextString(m) }
func (*AguaclaraPacketData) ProtoMessage()    {}
func (*AguaclaraPacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f61947fc7e84c630, []int{0}
}
func (m *AguaclaraPacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AguaclaraPacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AguaclaraPacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AguaclaraPacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AguaclaraPacketData.Merge(m, src)
}
func (m *AguaclaraPacketData) XXX_Size() int {
	return m.Size()
}
func (m *AguaclaraPacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_AguaclaraPacketData.DiscardUnknown(m)
}

var xxx_messageInfo_AguaclaraPacketData proto.InternalMessageInfo

func (m *AguaclaraPacketData) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *AguaclaraPacketData) GetTokenAddress() string {
	if m != nil {
		return m.TokenAddress
	}
	return ""
}

func (m *AguaclaraPacketData) GetTokenId() string {
	if m != nil {
		return m.TokenId
	}
	return ""
}

func (m *AguaclaraPacketData) GetDidRecipient() string {
	if m != nil {
		return m.DidRecipient
	}
	return ""
}

func (m *AguaclaraPacketData) GetToMetadata() string {
	if m != nil {
		return m.ToMetadata
	}
	return ""
}

func (m *AguaclaraPacketData) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *AguaclaraPacketData) GetCurrentChainId() string {
	if m != nil {
		return m.CurrentChainId
	}
	return ""
}

func (m *AguaclaraPacketData) GetRecipientChainId() string {
	if m != nil {
		return m.RecipientChainId
	}
	return ""
}

type NoData struct {
}

func (m *NoData) Reset()         { *m = NoData{} }
func (m *NoData) String() string { return proto.CompactTextString(m) }
func (*NoData) ProtoMessage()    {}
func (*NoData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f61947fc7e84c630, []int{1}
}
func (m *NoData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NoData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NoData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NoData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoData.Merge(m, src)
}
func (m *NoData) XXX_Size() int {
	return m.Size()
}
func (m *NoData) XXX_DiscardUnknown() {
	xxx_messageInfo_NoData.DiscardUnknown(m)
}

var xxx_messageInfo_NoData proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AguaclaraPacketData)(nil), "ElectronicSignaturesIndustries.anconprotocol.aguaclara.AguaclaraPacketData")
	proto.RegisterType((*NoData)(nil), "ElectronicSignaturesIndustries.anconprotocol.aguaclara.NoData")
}

func init() { proto.RegisterFile("aguaclara/packet.proto", fileDescriptor_f61947fc7e84c630) }

var fileDescriptor_f61947fc7e84c630 = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x4f, 0x4b, 0xfb, 0x30,
	0x18, 0xc7, 0xd7, 0xfd, 0xf6, 0xdb, 0x66, 0x10, 0x91, 0x08, 0x92, 0x53, 0x90, 0x1d, 0x44, 0x84,
	0xb5, 0x07, 0xc1, 0xfb, 0xfc, 0x73, 0x18, 0xa8, 0xc8, 0xbc, 0x79, 0x7b, 0x96, 0xc4, 0x35, 0xac,
	0x26, 0x25, 0x79, 0x0a, 0xfa, 0x2e, 0xbc, 0xfa, 0x8e, 0x3c, 0xee, 0xe8, 0x51, 0xda, 0x37, 0x22,
	0xcd, 0xac, 0x9d, 0x7a, 0xeb, 0xf7, 0x5f, 0x1e, 0xe8, 0x87, 0xec, 0xc3, 0xa2, 0x00, 0x91, 0x81,
	0x83, 0x24, 0x07, 0xb1, 0x54, 0x18, 0xe7, 0xce, 0xa2, 0xa5, 0xa7, 0x97, 0x99, 0x12, 0xe8, 0xac,
	0xd1, 0xe2, 0x4e, 0x2f, 0x0c, 0x60, 0xe1, 0x94, 0x9f, 0x1a, 0x59, 0x78, 0x74, 0x5a, 0xf9, 0x18,
	0x8c, 0xb0, 0x26, 0x54, 0x85, 0xcd, 0xe2, 0xef, 0x47, 0x46, 0xaf, 0x5d, 0xb2, 0x37, 0x69, 0xd4,
	0x6d, 0x78, 0xf1, 0x02, 0x10, 0x28, 0x23, 0x03, 0xe1, 0x14, 0xa0, 0x75, 0x2c, 0x3a, 0x88, 0x8e,
	0xb6, 0x66, 0x8d, 0xa4, 0x23, 0xb2, 0x8d, 0x76, 0xa9, 0xcc, 0x44, 0x4a, 0xa7, 0xbc, 0x67, 0xdd,
	0x10, 0xff, 0xf0, 0xea, 0x75, 0xd0, 0x53, 0xc9, 0xfe, 0xad, 0xd7, 0x5f, 0xb2, 0x5e, 0x4b, 0x2d,
	0x67, 0x4a, 0xe8, 0x5c, 0x2b, 0x83, 0xac, 0xb7, 0x5e, 0x6f, 0x7a, 0x94, 0x13, 0x82, 0xf6, 0x5a,
	0x21, 0x48, 0x40, 0x60, 0xff, 0x43, 0x63, 0xc3, 0xa1, 0x94, 0xf4, 0x52, 0xf0, 0x29, 0xeb, 0x87,
	0x24, 0x7c, 0xd3, 0x43, 0xb2, 0x23, 0x0a, 0xe7, 0x94, 0xc1, 0xf3, 0x14, 0x74, 0x7d, 0x78, 0x10,
	0xd2, 0x5f, 0x2e, 0x3d, 0x26, 0xbb, 0xae, 0x39, 0xd4, 0x34, 0x87, 0xa1, 0xf9, 0xc7, 0x1f, 0x0d,
	0x49, 0xff, 0xc6, 0xd6, 0x7f, 0xe3, 0xec, 0xe1, 0xad, 0xe4, 0xd1, 0xaa, 0xe4, 0xd1, 0x47, 0xc9,
	0xa3, 0x97, 0x8a, 0x77, 0x56, 0x15, 0xef, 0xbc, 0x57, 0xbc, 0x73, 0x7f, 0xb5, 0xd0, 0x98, 0x16,
	0xf3, 0x58, 0xd8, 0xc7, 0xa4, 0x45, 0x30, 0x6e, 0x19, 0x8c, 0x5b, 0x08, 0x49, 0x80, 0x30, 0x6e,
	0x28, 0x24, 0x4f, 0x49, 0x0b, 0x13, 0x9f, 0x73, 0xe5, 0xe7, 0xfd, 0x90, 0x9d, 0x7c, 0x06, 0x00,
	0x00, 0xff, 0xff, 0xc4, 0x98, 0xae, 0x42, 0xe6, 0x01, 0x00, 0x00,
}

func (m *AguaclaraPacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AguaclaraPacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AguaclaraPacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RecipientChainId) > 0 {
		i -= len(m.RecipientChainId)
		copy(dAtA[i:], m.RecipientChainId)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.RecipientChainId)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.CurrentChainId) > 0 {
		i -= len(m.CurrentChainId)
		copy(dAtA[i:], m.CurrentChainId)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.CurrentChainId)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.ToMetadata) > 0 {
		i -= len(m.ToMetadata)
		copy(dAtA[i:], m.ToMetadata)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.ToMetadata)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.DidRecipient) > 0 {
		i -= len(m.DidRecipient)
		copy(dAtA[i:], m.DidRecipient)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.DidRecipient)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.TokenId) > 0 {
		i -= len(m.TokenId)
		copy(dAtA[i:], m.TokenId)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.TokenId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TokenAddress) > 0 {
		i -= len(m.TokenAddress)
		copy(dAtA[i:], m.TokenAddress)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.TokenAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *NoData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NoData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NoData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintPacket(dAtA []byte, offset int, v uint64) int {
	offset -= sovPacket(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AguaclaraPacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.TokenAddress)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.TokenId)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.DidRecipient)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.ToMetadata)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.CurrentChainId)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.RecipientChainId)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}

func (m *NoData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovPacket(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPacket(x uint64) (n int) {
	return sovPacket(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AguaclaraPacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AguaclaraPacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AguaclaraPacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DidRecipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DidRecipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToMetadata", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ToMetadata = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CurrentChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecipientChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RecipientChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NoData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NoData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NoData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPacket(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPacket
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPacket
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPacket
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPacket        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPacket          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPacket = fmt.Errorf("proto: unexpected end of group")
)
