# This is a basic workflow that is manually triggered

name: anconprotocol

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, pull_request]

# This workflow makes x86_64 binaries for mac, windows, and linux.

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
        targetos: [windows, darwin, linux]
    name: anconprotocol ${{ matrix.arch }} for ${{ matrix.targetos }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}

      - name: Test Ancon
        run: |
          cd x/anconprotocol/keeper
          go test

      - name: Test Mintswap
        run: |
          cd x/mintswap/keeper
          go test
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: anconprotocold ${{ matrix.targetos }} ${{ matrix.arch }}
      #     path: cmd/anconprotocold/anconprotocold

